name: flutter_localized_locales
description: Locale code to name mappings for several languages
version: 1.0.0
author: Pierre-Louis Guidez <plg@google.com>
homepage: https://github.com/guidezpl/flutter-localized-locales

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.2

flutter:
   assets:
    - data/
    - languages.json
