name: flutter_localized_locales
description: Flutter plugin which provides locale code to name mappings for 563 locales.
version: 2.0.0-nullsafety
homepage: https://github.com/guidezpl/flutter-localized-locales

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.2

flutter:
  assets:
    - data/af.json
    - data/af_NA.json
    - data/af_ZA.json
    - data/ak.json
    - data/ak_GH.json
    - data/am.json
    - data/am_ET.json
    - data/ar.json
    - data/ar_AE.json
    - data/ar_BH.json
    - data/ar_DJ.json
    - data/ar_DZ.json
    - data/ar_EG.json
    - data/ar_EH.json
    - data/ar_ER.json
    - data/ar_IL.json
    - data/ar_IQ.json
    - data/ar_JO.json
    - data/ar_KM.json
    - data/ar_KW.json
    - data/ar_LB.json
    - data/ar_LY.json
    - data/ar_MA.json
    - data/ar_MR.json
    - data/ar_OM.json
    - data/ar_PS.json
    - data/ar_QA.json
    - data/ar_SA.json
    - data/ar_SD.json
    - data/ar_SO.json
    - data/ar_SS.json
    - data/ar_SY.json
    - data/ar_TD.json
    - data/ar_TN.json
    - data/ar_YE.json
    - data/as.json
    - data/as_IN.json
    - data/az.json
    - data/az_AZ.json
    - data/az_Cyrl.json
    - data/az_Cyrl_AZ.json
    - data/az_Latn.json
    - data/az_Latn_AZ.json
    - data/be.json
    - data/be_BY.json
    - data/bg.json
    - data/bg_BG.json
    - data/bm.json
    - data/bm_Latn.json
    - data/bm_Latn_ML.json
    - data/bn.json
    - data/bn_BD.json
    - data/bn_IN.json
    - data/bo.json
    - data/bo_CN.json
    - data/bo_IN.json
    - data/br.json
    - data/br_FR.json
    - data/bs.json
    - data/bs_BA.json
    - data/bs_Cyrl.json
    - data/bs_Cyrl_BA.json
    - data/bs_Latn.json
    - data/bs_Latn_BA.json
    - data/ca.json
    - data/ca_AD.json
    - data/ca_ES.json
    - data/ca_FR.json
    - data/ca_IT.json
    - data/cs.json
    - data/cs_CZ.json
    - data/cy.json
    - data/cy_GB.json
    - data/da.json
    - data/da_DK.json
    - data/da_GL.json
    - data/de.json
    - data/de_AT.json
    - data/de_BE.json
    - data/de_CH.json
    - data/de_DE.json
    - data/de_LI.json
    - data/de_LU.json
    - data/dz.json
    - data/dz_BT.json
    - data/ee.json
    - data/ee_GH.json
    - data/ee_TG.json
    - data/el.json
    - data/el_CY.json
    - data/el_GR.json
    - data/en.json
    - data/en_AG.json
    - data/en_AI.json
    - data/en_AS.json
    - data/en_AU.json
    - data/en_BB.json
    - data/en_BE.json
    - data/en_BM.json
    - data/en_BS.json
    - data/en_BW.json
    - data/en_BZ.json
    - data/en_CA.json
    - data/en_CC.json
    - data/en_CK.json
    - data/en_CM.json
    - data/en_CX.json
    - data/en_DG.json
    - data/en_DM.json
    - data/en_ER.json
    - data/en_FJ.json
    - data/en_FK.json
    - data/en_FM.json
    - data/en_GB.json
    - data/en_GD.json
    - data/en_GG.json
    - data/en_GH.json
    - data/en_GI.json
    - data/en_GM.json
    - data/en_GU.json
    - data/en_GY.json
    - data/en_HK.json
    - data/en_IE.json
    - data/en_IM.json
    - data/en_IN.json
    - data/en_IO.json
    - data/en_JE.json
    - data/en_JM.json
    - data/en_KE.json
    - data/en_KI.json
    - data/en_KN.json
    - data/en_KY.json
    - data/en_LC.json
    - data/en_LR.json
    - data/en_LS.json
    - data/en_MG.json
    - data/en_MH.json
    - data/en_MO.json
    - data/en_MP.json
    - data/en_MS.json
    - data/en_MT.json
    - data/en_MU.json
    - data/en_MW.json
    - data/en_MY.json
    - data/en_NA.json
    - data/en_NF.json
    - data/en_NG.json
    - data/en_NR.json
    - data/en_NU.json
    - data/en_NZ.json
    - data/en_PG.json
    - data/en_PH.json
    - data/en_PK.json
    - data/en_PN.json
    - data/en_PR.json
    - data/en_PW.json
    - data/en_RW.json
    - data/en_SB.json
    - data/en_SC.json
    - data/en_SD.json
    - data/en_SG.json
    - data/en_SH.json
    - data/en_SL.json
    - data/en_SS.json
    - data/en_SX.json
    - data/en_SZ.json
    - data/en_TC.json
    - data/en_TK.json
    - data/en_TO.json
    - data/en_TT.json
    - data/en_TV.json
    - data/en_TZ.json
    - data/en_UG.json
    - data/en_UM.json
    - data/en_US.json
    - data/en_VC.json
    - data/en_VG.json
    - data/en_VI.json
    - data/en_VU.json
    - data/en_WS.json
    - data/en_ZA.json
    - data/en_ZM.json
    - data/en_ZW.json
    - data/eo.json
    - data/es.json
    - data/es_AR.json
    - data/es_BO.json
    - data/es_CL.json
    - data/es_CO.json
    - data/es_CR.json
    - data/es_CU.json
    - data/es_DO.json
    - data/es_EA.json
    - data/es_EC.json
    - data/es_ES.json
    - data/es_GQ.json
    - data/es_GT.json
    - data/es_HN.json
    - data/es_IC.json
    - data/es_MX.json
    - data/es_NI.json
    - data/es_PA.json
    - data/es_PE.json
    - data/es_PH.json
    - data/es_PR.json
    - data/es_PY.json
    - data/es_SV.json
    - data/es_US.json
    - data/es_UY.json
    - data/es_VE.json
    - data/et.json
    - data/et_EE.json
    - data/eu.json
    - data/eu_ES.json
    - data/fa.json
    - data/fa_AF.json
    - data/fa_IR.json
    - data/ff.json
    - data/ff_CM.json
    - data/ff_GN.json
    - data/ff_MR.json
    - data/ff_SN.json
    - data/fi.json
    - data/fi_FI.json
    - data/fo.json
    - data/fo_FO.json
    - data/fr.json
    - data/fr_BE.json
    - data/fr_BF.json
    - data/fr_BI.json
    - data/fr_BJ.json
    - data/fr_BL.json
    - data/fr_CA.json
    - data/fr_CD.json
    - data/fr_CF.json
    - data/fr_CG.json
    - data/fr_CH.json
    - data/fr_CI.json
    - data/fr_CM.json
    - data/fr_DJ.json
    - data/fr_DZ.json
    - data/fr_FR.json
    - data/fr_GA.json
    - data/fr_GF.json
    - data/fr_GN.json
    - data/fr_GP.json
    - data/fr_GQ.json
    - data/fr_HT.json
    - data/fr_KM.json
    - data/fr_LU.json
    - data/fr_MA.json
    - data/fr_MC.json
    - data/fr_MF.json
    - data/fr_MG.json
    - data/fr_ML.json
    - data/fr_MQ.json
    - data/fr_MR.json
    - data/fr_MU.json
    - data/fr_NC.json
    - data/fr_NE.json
    - data/fr_PF.json
    - data/fr_PM.json
    - data/fr_RE.json
    - data/fr_RW.json
    - data/fr_SC.json
    - data/fr_SN.json
    - data/fr_SY.json
    - data/fr_TD.json
    - data/fr_TG.json
    - data/fr_TN.json
    - data/fr_VU.json
    - data/fr_WF.json
    - data/fr_YT.json
    - data/fy.json
    - data/fy_NL.json
    - data/ga.json
    - data/ga_IE.json
    - data/gd.json
    - data/gd_GB.json
    - data/gl.json
    - data/gl_ES.json
    - data/gu.json
    - data/gu_IN.json
    - data/gv.json
    - data/gv_IM.json
    - data/ha.json
    - data/ha_GH.json
    - data/ha_Latn.json
    - data/ha_Latn_GH.json
    - data/ha_Latn_NE.json
    - data/ha_Latn_NG.json
    - data/ha_NE.json
    - data/ha_NG.json
    - data/he.json
    - data/he_IL.json
    - data/hi.json
    - data/hi_IN.json
    - data/hr.json
    - data/hr_BA.json
    - data/hr_HR.json
    - data/hu.json
    - data/hu_HU.json
    - data/hy.json
    - data/hy_AM.json
    - data/id.json
    - data/id_ID.json
    - data/ig.json
    - data/ig_NG.json
    - data/ii.json
    - data/ii_CN.json
    - data/is.json
    - data/is_IS.json
    - data/it.json
    - data/it_CH.json
    - data/it_IT.json
    - data/it_SM.json
    - data/ja.json
    - data/ja_JP.json
    - data/ka.json
    - data/ka_GE.json
    - data/ki.json
    - data/ki_KE.json
    - data/kk.json
    - data/kk_Cyrl.json
    - data/kk_Cyrl_KZ.json
    - data/kk_KZ.json
    - data/kl.json
    - data/kl_GL.json
    - data/km.json
    - data/km_KH.json
    - data/kn.json
    - data/kn_IN.json
    - data/ko.json
    - data/ko_KP.json
    - data/ko_KR.json
    - data/ks.json
    - data/ks_Arab.json
    - data/ks_Arab_IN.json
    - data/ks_IN.json
    - data/kw.json
    - data/kw_GB.json
    - data/ky.json
    - data/ky_Cyrl.json
    - data/ky_Cyrl_KG.json
    - data/ky_KG.json
    - data/lb.json
    - data/lb_LU.json
    - data/lg.json
    - data/lg_UG.json
    - data/ln.json
    - data/ln_AO.json
    - data/ln_CD.json
    - data/ln_CF.json
    - data/ln_CG.json
    - data/lo.json
    - data/lo_LA.json
    - data/lt.json
    - data/lt_LT.json
    - data/lu.json
    - data/lu_CD.json
    - data/lv.json
    - data/lv_LV.json
    - data/mg.json
    - data/mg_MG.json
    - data/mk.json
    - data/mk_MK.json
    - data/ml.json
    - data/ml_IN.json
    - data/mn.json
    - data/mn_Cyrl.json
    - data/mn_Cyrl_MN.json
    - data/mn_MN.json
    - data/mr.json
    - data/mr_IN.json
    - data/ms.json
    - data/ms_BN.json
    - data/ms_Latn.json
    - data/ms_Latn_BN.json
    - data/ms_Latn_MY.json
    - data/ms_Latn_SG.json
    - data/ms_MY.json
    - data/ms_SG.json
    - data/mt.json
    - data/mt_MT.json
    - data/my.json
    - data/my_MM.json
    - data/nb.json
    - data/nb_NO.json
    - data/nb_SJ.json
    - data/nd.json
    - data/nd_ZW.json
    - data/ne.json
    - data/ne_IN.json
    - data/ne_NP.json
    - data/nl.json
    - data/nl_AW.json
    - data/nl_BE.json
    - data/nl_BQ.json
    - data/nl_CW.json
    - data/nl_NL.json
    - data/nl_SR.json
    - data/nl_SX.json
    - data/nn.json
    - data/nn_NO.json
    - data/no.json
    - data/no_NO.json
    - data/om.json
    - data/om_ET.json
    - data/om_KE.json
    - data/or.json
    - data/or_IN.json
    - data/os.json
    - data/os_GE.json
    - data/os_RU.json
    - data/pa.json
    - data/pa_Arab.json
    - data/pa_Arab_PK.json
    - data/pa_Guru.json
    - data/pa_Guru_IN.json
    - data/pa_IN.json
    - data/pa_PK.json
    - data/pl.json
    - data/pl_PL.json
    - data/ps.json
    - data/ps_AF.json
    - data/pt.json
    - data/pt_AO.json
    - data/pt_BR.json
    - data/pt_CV.json
    - data/pt_GW.json
    - data/pt_MO.json
    - data/pt_MZ.json
    - data/pt_PT.json
    - data/pt_ST.json
    - data/pt_TL.json
    - data/qu.json
    - data/qu_BO.json
    - data/qu_EC.json
    - data/qu_PE.json
    - data/rm.json
    - data/rm_CH.json
    - data/rn.json
    - data/rn_BI.json
    - data/ro.json
    - data/ro_MD.json
    - data/ro_RO.json
    - data/ru.json
    - data/ru_BY.json
    - data/ru_KG.json
    - data/ru_KZ.json
    - data/ru_MD.json
    - data/ru_RU.json
    - data/ru_UA.json
    - data/rw.json
    - data/rw_RW.json
    - data/se.json
    - data/se_FI.json
    - data/se_NO.json
    - data/se_SE.json
    - data/sg.json
    - data/sg_CF.json
    - data/sh.json
    - data/sh_BA.json
    - data/si.json
    - data/si_LK.json
    - data/sk.json
    - data/sk_SK.json
    - data/sl.json
    - data/sl_SI.json
    - data/sn.json
    - data/sn_ZW.json
    - data/so.json
    - data/so_DJ.json
    - data/so_ET.json
    - data/so_KE.json
    - data/so_SO.json
    - data/sq.json
    - data/sq_AL.json
    - data/sq_MK.json
    - data/sq_XK.json
    - data/sr.json
    - data/sr_BA.json
    - data/sr_Cyrl.json
    - data/sr_Cyrl_BA.json
    - data/sr_Cyrl_ME.json
    - data/sr_Cyrl_RS.json
    - data/sr_Cyrl_XK.json
    - data/sr_Latn.json
    - data/sr_Latn_BA.json
    - data/sr_Latn_ME.json
    - data/sr_Latn_RS.json
    - data/sr_Latn_XK.json
    - data/sr_ME.json
    - data/sr_RS.json
    - data/sr_XK.json
    - data/sv.json
    - data/sv_AX.json
    - data/sv_FI.json
    - data/sv_SE.json
    - data/sw.json
    - data/sw_KE.json
    - data/sw_TZ.json
    - data/sw_UG.json
    - data/ta.json
    - data/ta_IN.json
    - data/ta_LK.json
    - data/ta_MY.json
    - data/ta_SG.json
    - data/te.json
    - data/te_IN.json
    - data/th.json
    - data/th_TH.json
    - data/ti.json
    - data/ti_ER.json
    - data/ti_ET.json
    - data/tl.json
    - data/tl_PH.json
    - data/to.json
    - data/to_TO.json
    - data/tr.json
    - data/tr_CY.json
    - data/tr_TR.json
    - data/ug.json
    - data/ug_Arab.json
    - data/ug_Arab_CN.json
    - data/ug_CN.json
    - data/uk.json
    - data/uk_UA.json
    - data/ur.json
    - data/ur_IN.json
    - data/ur_PK.json
    - data/uz.json
    - data/uz_AF.json
    - data/uz_Arab.json
    - data/uz_Arab_AF.json
    - data/uz_Cyrl.json
    - data/uz_Cyrl_UZ.json
    - data/uz_Latn.json
    - data/uz_Latn_UZ.json
    - data/uz_UZ.json
    - data/vi.json
    - data/vi_VN.json
    - data/yi.json
    - data/yo.json
    - data/yo_BJ.json
    - data/yo_NG.json
    - data/zh.json
    - data/zh_CN.json
    - data/zh_HK.json
    - data/zh_Hans.json
    - data/zh_Hans_CN.json
    - data/zh_Hans_HK.json
    - data/zh_Hans_MO.json
    - data/zh_Hans_SG.json
    - data/zh_Hant.json
    - data/zh_Hant_HK.json
    - data/zh_Hant_MO.json
    - data/zh_Hant_TW.json
    - data/zh_MO.json
    - data/zh_SG.json
    - data/zh_TW.json
    - data/zu.json
    - data/zu_ZA.json
