name: flutter_localized_locales
description: Flutter plugin which provides locale code to name mappings for 563 locales.
version: 1.2.0-nullsafety.1
homepage: https://github.com/guidezpl/flutter-localized-locales

environment:
  sdk: ">=2.10.0-0.0.dev"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.2

flutter:
   assets:
    - data/
