// Generated by tool/build.sh
const all_native_names = {
  "en": "English",
  "en_US": "English (United States)",
  "zh": "中文",
  "zh_CN": "中文 (中国)",
  "zh_HK": "中文 (中国香港特别行政区)",
  "zh_Hans": "中文 (简体中文)",
  "zh_Hans_CN": "中文 (简体中文, 中国)",
  "zh_Hant": "中文 (繁體)",
  "zh_Hant_HK": "中文 (繁體字, 中華人民共和國香港特別行政區)",
  "zh_Hant_MO": "中文 (繁體, 中華人民共和國澳門特別行政區)",
  "zh_Hant_TW": "中文 (繁體, 台灣)",
};
